Repository kf5i/k3ai-core, pull requests merged in 2020-11, with the labels that each got.

#51 refactor data repository
  cmd/tools/cli/integration_test.go
  internal/plugins/groups_test.go
  internal/plugins/plugins_test.go
  internal/plugins/remote_contents_test.go
  internal/plugins/shared_test.go
  internal/plugins/testdata/defaults/plugin.yaml
  internal/plugins/testdata/groups/two_plugins/group.yaml
  local_repo/core/groups/argo/group.yaml
  local_repo/core/plugins/argo-workflow-traefik/plugin.yaml
Labels: approved

#52 Add inline plugins for the groups
  cmd/tools/cli/apply.go
  cmd/tools/cli/delete.go
  cmd/tools/cli/integration_test.go
  internal/plugins/groups.go
  internal/plugins/groups_test.go
  internal/plugins/remote_contents_test.go
  local_repo/core/groups/argo-workflow/group.yaml
  local_repo/core/groups/argo/group.yaml
Labels: approved

#56 Config home
  cmd/tools/cli/cli.go
  go.mod
  go.sum
  internal/plugins/groups.go
  internal/plugins/plugins.go
  internal/plugins/shared.go
  internal/settings/config.go
  internal/settings/config_test.go
  internal/shared/common_tests_functions.go
  internal/shared/commons.go
Labels: approved, work-in-progress/do-not-merge

#47 Add ability to wait on specified labels
  Makefile
  cmd/tools/cli/apply.go
  cmd/tools/cli/delete.go
  internal/k8s/kctl/deploy.go
  internal/k8s/kctl/wait.go
  internal/plugins/plugins_test.go
Labels: WIP

#57 WIP: Scaffold a basic web ui for k3ai
  .gitignore
  cmd/tools/web-ui/assets/components/Card.js
  cmd/tools/web-ui/assets/components/PageLayout.js
  cmd/tools/web-ui/assets/index.html
  cmd/tools/web-ui/assets/index.js
  cmd/tools/web-ui/assets/style.pcss
  cmd/tools/web-ui/dist/assets.64015913.js
  cmd/tools/web-ui/dist/assets.64015913.js.map
  cmd/tools/web-ui/dist/index.html
  cmd/tools/web-ui/dist/style.4dd92d98.css
  cmd/tools/web-ui/dist/style.4dd92d98.css.map
  cmd/tools/web-ui/package-lock.json
  cmd/tools/web-ui/package.json
  cmd/tools/web-ui/postcss.config.js
  cmd/tools/web-ui/server.go
  go.mod
  go.sum
Labels: approved, area/core, ena

#61 Aggregate repo url
  cmd/commands/handling.go
  cmd/tools/cli/apply.go
  cmd/tools/cli/cli.go
  cmd/tools/cli/delete.go
  cmd/tools/cli/integration_test.go
  cmd/tools/cli/list.go
  cmd/tools/web-ui/server.go
  internal/plugins/groups.go
  internal/plugins/groups_test.go
  internal/plugins/plugins.go
  internal/plugins/plugins_test.go
  internal/plugins/remote_contents.go
  internal/plugins/remote_contents_test.go
  internal/settings/config.go
  internal/settings/config_test.go
  internal/shared/commons.go
  local_repo/core/groups/argo-workflow/group.yaml
Labels: work-in-progress/do-not-merge

#64 Fix local repo
  cmd/tools/cli/formatting.go
  cmd/tools/cli/list.go
  cmd/tools/web-ui/server.go
  internal/plugins/groups.go
  internal/plugins/plugins.go
  internal/plugins/remote_contents.go
  internal/plugins/remote_contents_test.go
  internal/plugins/shared.go
  local_repo/core/groups/argo-workflow/group.yaml
  local_repo/core/plugins/argo-workflow-no-defaults/plugin.yaml
  local_repo/core/plugins/argo-workflow-ns/plugin.yaml
  local_repo/core/plugins/argo-workflow-traefik/plugin.yaml
Labels: approved
