Repository kf5i/k3ai-core, pull requests merged in 2020-10, with the labels that each got.

#4 Add CI using Github actions
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .goreleaser.yaml
  Makefile
  pkg/plugins/manage.go
Labels: approved, enhancement

#5 Add cobra for building out the cli
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .goreleaser.yaml
  Makefile
  cmd/tools/cli/cli.go
  cmd/tools/cli/version.go
  cmd/tools/cli/version_test.go
  go.mod
  go.sum
  main.go
  pkg/k8s/kctl/deploy.go
Labels: enhancement

#9 Set version info during build
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .goreleaser.yaml
  cmd/tools/cli/version.go
Labels: approved, enhancement

#16 Add apply, delete and list commands
  cmd/tools/cli/apply.go
  cmd/tools/cli/cli.go
  cmd/tools/cli/delete.go
  cmd/tools/cli/list.go
  internal/k8s/kctl/config.go
  internal/k8s/kctl/deploy.go
  internal/plugins/manage.go
  internal/plugins/manage_test.go
  internal/plugins/plugin_spec.go
  internal/plugins/plugin_spec_test.go
  main.go
Labels: approved, enhancement

#26 Hide usage info for cmd errors
  cmd/tools/cli/cli.go
  internal/k8s/kctl/deploy.go
Labels: approved

#24 Add a costant name for plugins
  internal/plugins/manage.go
  internal/plugins/manage_test.go
  internal/plugins/plugin_spec.go
  internal/plugins/plugin_spec_test.go
  internal/plugins/testdata/defaults/plugin.yaml
  internal/plugins/testdata/empty_defaults/plugin.yaml
Labels: approved

#27 Add ability to use kubectl directly
  cmd/tools/cli/cli.go
  internal/k8s/kctl/config.go
  internal/k8s/kctl/deploy.go
Labels: approved, enhancement

#37 Change name space level
  go.sum
  internal/k8s/kctl/deploy.go
  internal/plugins/plugin_spec.go
  internal/plugins/plugin_spec_test.go
  internal/plugins/testdata/defaults/plugin.yaml
Labels: approved

#42 Add plugins group
  cmd/tools/cli/apply.go
  cmd/tools/cli/cli.go
  cmd/tools/cli/delete.go
  cmd/tools/cli/list.go
  go.sum
  internal/k8s/kctl/deploy.go
  internal/plugins/groups.go
  internal/plugins/groups_test.go
  internal/plugins/manage.go
  internal/plugins/manage_test.go
  internal/plugins/plugin_spec.go
  internal/plugins/plugins.go
  internal/plugins/plugins_test.go
  internal/plugins/remote_contents.go
  internal/plugins/remote_contents_test.go
  internal/plugins/shared.go
  internal/plugins/testdata/groups/two_plugins/group.yaml
Labels: approved

#49 Make list consistent with apply and delete
  cmd/tools/cli/apply.go
  cmd/tools/cli/cli.go
  cmd/tools/cli/delete.go
  cmd/tools/cli/list.go
Labels: approved

#48 Add basic integration test setup using kind
  .github/workflows/ci.yaml
  Makefile
  cmd/tools/cli/apply.go
  cmd/tools/cli/cli.go
  cmd/tools/cli/delete.go
  cmd/tools/cli/integration_test.go
  cmd/tools/cli/list.go
Labels: approved
